### ISSUE TITLE
error when running test_seglink.py

### ISSUE THREAD

**Issue by InesBeltaief** [dengdan/seglink#15]
I have successfully convert SynthText and ICDAR2015 datasets to tfrecords but when I try to test_seglink.py I got the following error !
`AttributeError: 'NoneType' object has no attribute 'startswith'
`

**Comment by dengdan** [comment]
Please provide your command and error msg in detail.

**Comment by shaohailin** [comment]
i execute test_seglink.py ,i got this error too.   
AttributeError: 'NoneType' object has no attribute 'startswith' 
because i set   'checkpoint_path', None  on pycharm
when i make it   'checkpoint_path', util.io.get_absolute_path('~/code/seglink-master-pixelLinkimplemented/seglink-master/models/512/model.ckpt-217867')
it runs 
maybe help you
