### ISSUE TITLE
hi, "import util" can not find the module

### ISSUE THREAD

**Issue by deepinsights** [dengdan/seglink#2]

**Comment by dengdan** [comment]
The `util` module comes from https://github.com/dengdan/pylib.  It's a submodule containing a lot of python methods encapsulated from many common used build-in modules(os, sys, etc.) or popular libs (numpy, tensorflow, cv2, etc. ).  It should be added to seglink project as a submodule, but I haven't done it yet, because I am still adding or modifying code to/of it. You can clone `pylib`, and add the `src` folder to you `PYTHONPATH`.
